---
title: "mSigAct_Twinstrand"
author: "Arnoud"
date: "December 11, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#devtools::install_github("steverozen/mSigAct",ref="master")
# library(mSigAct)
library(ICAMS)

setwd(devtools::package_file(
  "data-raw", 
  "Twinstrand_mSigAct-from-arnoud-2019-12-11"))


## load the catalog
load("TwinstrandSBScatalog.RData")
cat<-SBScat$catSBS96
```

```{r perform abundance normalization PCAWG signatures}
load("Twinstrand_abundance.RData")


## prep signature universe
universe<-read.csv("PCAWG7.tsv",sep="\t",as.is=T)
rownames(universe)<-gsub(">","",universe$Mutation.Type)
universe<-universe[,-1]
sigs <- paste0('SBS',c(1,2,5,8,13,22,31,35,40))
universe<-universe[,sigs]

ICAMS::PlotCatalogToPdf(
  as.catalog(universe, catalog.type = "counts.signature"), 
  "universe.pdf")

for(i in 1:96){
  ii<-substr(rownames(universe),1,3)[i]
  universe[i,]<-universe[i,] /
    as.numeric(all.abundance$BSgenome.Hsapiens.1000genomes.hs37d5$genome$`96`[ii]) *
    as.numeric(Twinstrand_Opp3[ii])
}
universe<-as.matrix(sweep(universe,2,colSums(universe),"/"))
ICAMS::PlotCatalogToPdf(
  as.catalog(universe, catalog.type = "counts.signature"), 
  "universe2.pdf")

```


```{r Perform mSigAct analysis}
## create matrix to save the analysis results
## 
## 
orig.cat <- cat
cat <- cat[ , 9 , drop = F]


output<-matrix(0,ncol=ncol(universe)+2,nrow=ncol(cat)*2)
rownames(output)<-c(paste0(colnames(cat),"_WithSBS22"),
                    paste0(colnames(cat),"_WithoutSBS22"))
colnames(output)<-c(colnames(universe),"statistic","chisq.p")

## setting dispersion parameter at 10
m.opts<-DefaultManyOpts()
m.opts$nbinom.size<-10
m.opts$local.opts$maxeval <- 10000
m.opts$global.opts$maxeval <- 10000

# i <- 9

my.obj.fn <- function(exp, spectrum, sigs, nbinom.size) { 
  mSigAct::ObjFnBinomMaxLH2(exp, spectrum, sigs, nbinom.size, allow.no.round = TRUE)
}

for(i in 1:ncol(cat)){
  
  ## remove cisplatin from universe if not AB14_Blood
  if(colnames(cat)[i] == "Blood_AB14"){ 
    universe2<-universe
  } else {
    universe2<-universe[,!c(colnames(universe) %in% c("SBS31","SBS35"))]
  }
  # debug(mSigAct:::SignaturePresenceTest1)
  ii<-mSigAct:::SignaturePresenceTest1(spectrum = cat[,i],
                                       sigs = universe2,
                                       target.sig.index=
                                         which(colnames(universe2)==
                                                 "SBS22"),
                                       m.opts = m.opts,
                                       eval_f=
                                         my.obj.fn)
  
  ## export analysis results into the output object
  output[paste0(colnames(cat)[i],"_WithSBS22"),"statistic"]<-ii$statistic
  output[paste0(colnames(cat)[i],"_WithSBS22"),"chisq.p"]<-ii$chisq.p
  output[paste0(colnames(cat)[i],"_WithSBS22"),names(ii$exp.with)]<-
    as.numeric(ii$exp.with)
  output[paste0(colnames(cat)[i],"_WithoutSBS22"),names(ii$exp.without)]<-
    as.numeric(ii$exp.without)
  
  print(paste0("Finished with ",colnames(cat)[i]))
}
output<-as.data.frame(output)

write.table(output,file="mSigAct_output.v2",sep="\t",quote=F,row.names=F)
```

