
#' Background.info for cells used in Kucab et al, 2019.
#'
#' @name background.info
#'
#' @source \code{kucab.background.info} was estimated from the control spectra in \code{\link{kucab.control.spectra.ICAMS}}.
#'   
"kucab.background.info"



#' Mutational spectra of cisplatin exposed HepG2 cells.
#' 
#' @format An \code{\link[ICAMS]{ICAMS}} \code{counts} catalog.
#' 
"cisplatin.exposed.HepG2.96"


#' Tests of HepG2 background subtraction
#' 
#' @format A data table
#' 
#' @examples 
#' 
#' HepG2.bg.tests.no.noise[1:2, 1:10]
"HepG2.bg.tests.no.noise"

#' Demonstration data: an \code{\link[ICAMS]{ICAMS}} catalog.
#' 
#' @source Cite Alexandrov et al, 2019
#' 
#' @format An \code{\link[ICAMS]{ICAMS}} catalog with 
#' mutations from 35 biliary tract tumors.
"BTSG.WGS.PCAWG"

#' Kucab spectra -- 2 mutation label columns and 324 data columns.
#' 
#' The original format used in Xueqing ZOU's code.
#' 
#' The row order is "A[C>A]A" "A[C>A]C" "A[C>A]G" "A[C>A]T" "A[C>G]A" ...
#'
#' @source https://github.com/xqzou/Cell_MutagenSig
#' 
"kucab.sub.catalog"

#' Kucab et al., 2019 signatures in the row order as found on
#'
#' @source \url{https://data.mendeley.com/datasets/m7r4msjb4c/2#folder-9f2942fa-935b-4ac3-aa26-35784fb68a85}
#' 
#' The row labels are in column 1 in the order
#' 
#' A[C>A]A A[C>A]C A[C>A]G A[C>A]T C[C>A]A ...
#' 
"kucab.sigs.orig.row.order"

#' The 35 control spectra using the Kucab row order.
#' 
"kucab.control.spectra.kucab"

#' Kucab et al., 2019 signatures in the same row order as \code{\link{kucab.sub.catalog}}.
#' 
#' The mutation type is in column 1, e.g. A[C>A]A A[C>A]C A[C>A]G A[C>A]T A[C>G]A ...
#'
#' @source \url{https://data.mendeley.com/datasets/m7r4msjb4c/2#folder-9f2942fa-935b-4ac3-aa26-35784fb68a85}
#' 
"kucab.sigs"

#' Information on the control samples from Kucab et al., 2019
#' 
"kucab.muts.control"


#' Kucab et al., 2019 signatures as a standard \code{ICAMS} counts.signature catalog.
#'
#' @source https://github.com/xqzou/Cell_MutagenSig
#' 
"kucab.sigs.ICAMS"

#' Kucab et al., 2019 spectra as a standard \code{ICAMS} count catalog.
#'
#' @source https://github.com/xqzou/Cell_MutagenSig
#' 
"kucab.spectra.ICAMS"


#' Control spectra from Kucab et al., 2019
#' 
#' @format An \code{\link[ICAMS]{ICAMS}} \code{counts} catalog with 35 samples.
"kucab.control.spectra.ICAMS"

#' Resampled mutations counts for combinations of 2:4 \code{kucab.controls}.
#' 
#' @format A list with elements 2:4, each of which is a vector of 
#' 10,000 elements, each of which is the mean of total 
#' mutation counts of 2 to 4 control spectra.
"kucab.control.dist"

#' List of test data for background subtraction based on Kucab 2016 Methyleugenol.
#' 
#' Generated by \code{data-raw/prepare.BG.MEG.kucab.test.data.R}.
#'
"BG.MEG.kucab.bg.test"
